- id: shell-cmd-on-change
  name: shell-cmd-on-change
  description: Run a shell command when certain files changed after a `git pull`.
  entry: shell-cmd-on-change
  language: python
  language_version: python3.11
  pass_filenames: false
  stages: [post-merge, manual]
  always_run: true
  verbose: true
- id: remind-poetry-install
  name: remind-poetry-install
  description: Remind to run `poetry install` if `pyproject.toml` or `poetry.lock` changed after a `git pull`.
  entry: remind-poetry-install
  language: python
  language_version: python3.11
  pass_filenames: false
  stages: [post-merge, manual]
  always_run: true
  verbose: true
