- id: shell-cmd-on-change
  name: shell command on file changes
  description: Run a shell command when certain files change after a git pull.
  entry: shell-cmd-on-change
  language: python
  pass_filenames: false
  stages: [post-merge, manual]
  always_run: true
  verbose: true
