name: Unit Test
on:
  push:
    branches:
      - master
    paths:
      - "src/**.py"
      - "tests/**"
      - "requirements-dev.txt"
      - "requirements-test.txt"
  pull_request:
    paths:
      - "src/**.py"
      - "tests/**"
      - "requirements-dev.txt"
      - "requirements-test.txt"
  workflow_call:
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python and cache test dependencies
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "requirements-test.txt"
      - name: Install test dependencies
        run: pip install -r requirements-test.txt
      - name: Perform editable install on local package
        run: pip install -e .
      - name: Run unit tests
        run: pytest -v --cov=src --cov-report term-missing
